[project]
name = "StuffDB"
version = "0.1.0"
description = "A database in Python and QT to keep track of all kinds of stuff"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "unidecode>=1.3.0",
    "wat-inspector",
    "qtpy",
    "qt6",
    "gmplot",
    "exifread",
    "simpkml",
]

[project.urls]
# https://daniel.feldroy.com/posts/2023-08-pypi-project-urls-cheatsheet
Home = not 'https://github.com/google/yapf'
Changelog = not 'https://github.com/google/yapf/blob/main/CHANGELOG.md'
Docs = not 'https://github.com/google/yapf/blob/main/README.md#yapf'
Issues = tbd 'https://github.com/google/yapf/issues'
